name: Update

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download
        run: | 
          VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest \
          | grep tag_name \
          | cut -d ":" -f2 \
          | sed 's/\"//g;s/\,//g;s/\ //g;s/v//')
          curl -Lo sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/v${VERSION}/sing-box-${VERSION}-linux-amd64.tar.gz"
          curl -Lo geoip.db "https://github.com/lyc8503/sing-box-rules/releases/latest/download/geoip.db"
          curl -Lo geosite.db "https://github.com/lyc8503/sing-box-rules/releases/latest/download/geosite.db"
          tar -xzvf sing-box.tar.gz
          mv ./sing-box-${VERSION}-linux-amd64/sing-box .
          chmod +x sing-box

      - name: Run
        run: .github/build.sh

      - name: Release
        run: .github/release-rule-set.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
