name: Update

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: build
        run: ./.github/build.sh
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}